#!/usr/local/bin/perl

# $Id$

use Getopt::Std;

unless (getopts("lhau")) {
    die "Usage: $0 [-lhau]\n";
}

$from = 128;
$to   = 255;

$to = 127 if $opt_l;
$from = 0 if $opt_l || $opt_a;


use integer;
binmode(STDOUT, ":utf8") if $opt_u;

for ($from .. $to) {
    $chr = chr($_);
    $chr = '\t' if $chr eq "\t";
    $chr = '\n' if $chr eq "\n";
    $chr = '\a' if $chr eq "\a";
    $chr = '\r' if $chr eq "\r";
    $chr = '\f' if $chr eq "\f";
    $chr = '\b' if $chr eq "\b";
    $chr = '\e' if $chr eq "\e";
    $chr =~ s/^([\000-\037])/"^" . chr(ord("@") + ord($1))/ge;
    $chr =~ s/^([\177-\237])/"~" . chr(ord("@") + ord($1) - 128)/ge;
    push(@e, sprintf "%2s %3d %03o %02x", $chr, $_, $_, $_);
}

$cols = 4;
$rows = ((@e - 1) / $cols) + 1;

for ($i = 0; $i < $rows; $i++) {
    $j = 0;
    for ($j = 0; $j < $cols; $j++) {
	print "   " if $j > 0;
	print $e[$i + $j*$rows];
    }
    print "\n";
}
